spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/voting_system
    username: postgres
    password: victor
    driver-class-name: org.postgresql.Driver
